name: Build and Release Wallpapers

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick texlive-full

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install requirements
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Move wallpaper.sty to texmf-local
        run: |
          sudo mkdir -p /usr/local/texlive/texmf-local/tex/latex
          sudo cp wallpaper.sty /usr/local/texlive/texmf-local/tex/latex/
          sudo mktexlsr

      - name: Run wallpapers.py
        run: |
          source venv/bin/activate
          python wallpapers.py

      - name: Zip results folder
        run: |
          zip -r results.zip results

      - name: Zip results-inverted folder
        run: |
          zip -r results-inverted.zip results-inverted

      - name: Prepare individual files
        id: prepare_files
        run: |
          mkdir release_files
          find results -type f | while read file; do
            newname=$(echo "$file" | sed 's/results\///; s/\//-/g')
            cp "$file" "release_files/$newname"
          done
          echo "files=$(ls release_files | tr '\n' ',' | sed 's/,$//')"

      - name: Prepare individual files inverted
        id: prepare_files_inverted
        run: |
          mkdir release_files_inverted
          find results-inverted -type f | while read file; do
            newname=$(echo "$file" | sed 's/results-inverted\///; s/\//-/g')
            cp "$file" "release_files_inverted/inv_$newname"
          done
          echo "files=$(ls release_files_inverted | tr '\n' ',' | sed 's/,$//')"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
          files: |
            results-inverted.zip
            results.zip
            release_files/*
            release_files_inverted/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


#             echo "<img src=\"https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/$fname\" alt=\"$fname\" style=\"max-width:400px; margin-bottom:30px\"><br>" >> index.html

      - name: Build giant index.html
        run: |
          echo "<!DOCTYPE html><html><head><title>All Wallpapers</title></head><body style=\"justify-self: center; font-family: sans-serif\"><h1>All Wallpapers from <a href=\"https://github.com/SoneNiko/math-wallpapers\">math-wallpapers</a></h1>" > index.html
          for img in release_files/*.png; do
            fname=$(basename "$img")
            inv_fname="inv_$fname"
            echo "<h4 style=\"margin-bottom: 0px\">$fname ; $inv_fname</h4>" >> index.html
            echo "<img src=\"./$fname\" alt=\"$fname\" style=\"max-width:600px; margin-bottom:30px\"><br>" >> index.html
            echo "<img src=\"./$inv_fname\" alt=\"$inv_fname\" style=\"max-width:600px; margin-bottom:30px\"><br>" >> index.html
          done
          echo "</body></html>" >> index.html
          mv index.html release_files/
      
      - name: Create deploy folder
        run: |
          mkdir -p deploy
          cp -r release_files/* deploy/
          cp -r release_files_inverted/* deploy/
          cp release_files/index.html deploy/
      
      - name: Upload release_files as artifact
        id: uploading
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

          